name: Run AI Fixer

on:
  workflow_dispatch:

jobs:
  auto-heal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Auto-Healer
        uses: tharusha-kudagala/ai-auto-healer@v0.1
        with:
          pat: ${{ secrets.GH_PAT }}
          branch: main
