name: Run AI Fixer

on:
  push:
    branches:
      - main
jobs:
  auto-heal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AI Auto-Healer
        uses: tharusha-kudagala/auto-healer-plugin@v0.1
        with:
          pat: ${{ secrets.GH_PAT }}
          branch: main
